struct DataPsu {
	unsigned long long time;
	double    senseTime;
	double    main_volt;
	double    main_curr;
	double    main_pwr;
	double    pwr_volt;
	double    pwr_curr;
	double    pwr_pwr;
	double    sys_volt;
	double    sys_curr;
	double    sys_pwr;
	boolean  alive;
};
