struct DataAhrs {
	unsigned long long time;
	double    senseTime;
	double    gyrX;
	double    gyrY;
	double    gyrZ;
	double    accX;
	double    accY;
	double    accZ;
	double    magX;
	double    magY;
	double    magZ;
	double    tempertaure;
	double    barometric_pressure;
	double    phi;
	double    the;
	double    psi;
	boolean  alive;
};
