struct DataSFusion {
	unsigned long long time;
	float    gyrX;
	float    gyrY;
	float    gyrZ;
	float    accX;
	float    accY;
	float    accZ;
	float    magX;
	float    magY;
	float    magZ;
	float    temp;
	float    press;
	float    phi;
	float    the;
	float    psi;
	float    q0;
	float    q1;
	float    q2;
	float    q3;
	float    posN;
	float    posE;
	float    posD;
	float    speedN;
	float    speedE;
	float    speedD;
	float    windN;
	float    windE;
	float    windD;
	float    ssa;
	float    aoa;
	float    gamma;
	boolean  alive;
};
