struct DataRaiOut {
	unsigned long long time;
	double             senseTime;
	unsigned short     chnl[12];
	double             xi_setpoint;      // aka. aileron
	double             eta_setpoint;     // aka. elevator
	double             zeta_setpoint;    // aka. rudder
	double             throttle_setpoint;    // aka. throttle
	double             flaps_setpoint;    // aka. flaps
	unsigned short     flight_mode;
	unsigned short     flight_fct;
	boolean            alive;
};
