struct DataGps {
	unsigned long long time;
	float              senseTime;
	float              lat;
	float              lon;
	float              alt;
	float              speed;
	float              cog;
	float              dopP;
	float              dopH;
	float              dopV;
	unsigned short     sats;
	unsigned short     satsInView;
	unsigned short     fix;
	unsigned short     fixMode;
	unsigned short     second;
	unsigned short     minute;
	unsigned short     hour;
	unsigned short     day;
	unsigned short     month;
	unsigned short     year;
	float              variation;
	float              magX;
	float              magY;
	float              magZ;
	boolean            alive;
};
