struct DataGps {
	unsigned long long time;
	double              senseTime;
	double              latitude;
	double              longitude;
	double              alt_msl;
	double              groundspeed;
	double              course_over_ground;
	double              dop_position;
	double              dop_horizontal;
	double              dop_velocity;
	unsigned short     sats;
	unsigned short     sats_in_view;
	unsigned short     fix;
	unsigned short     fix_mode;
	unsigned short     second;
	unsigned short     minute;
	unsigned short     hour;
	unsigned short     day;
	unsigned short     month;
	unsigned short     year;
	double             variation;
	double             magX;
	double             magY;
	double             magZ;
	boolean            alive;
};
