struct DataAir {
	unsigned long long time;
	double    senseTime;
	double    dynamic_pressure;
	double    true_airspeed;
	double    indicated_airspeed;
	double    barometric_pressure;
	double    barometric_height;
	double    density;
	double    temperature;
	boolean  alive;
};
