struct DataRaiIn {
	unsigned long long  time;
	double              senseTime;
	unsigned short      chnl[12];
	double              roll;
	double              pitch;
	double              yaw;
	double              thr;
	unsigned short      flight_mode;
	unsigned short      flight_fct;
	boolean             alive;
};
