struct DataCtrl {
	unsigned long long time;
	double             xi_setpoint;      // aka. aileron
	double             eta_setpoint;     // aka. elevator
	double             zeta_setpoint;    // aka. rudder
	double             throttle_setpoint;    // aka. throttle
	double             flaps_setpoint;    // aka. flaps
	double             roll_setpoint;
	double             roll_rate_setpoint;
	double             pitch_setpoint;
	double             pitch_rate_setpoint;
	double             yaw_setpoint;
	double             yaw_rate_setpoint;
	double             tas_setpoint;
	double             tas_rate_setpoint;
	double             hgt_setpoint;
	double             hgt_rate_setpoint;
	unsigned short     flight_mode;
	unsigned short     flight_fct;
	boolean            alive;
};
