struct DataSFusion {
	unsigned long long time;
	double    p;
	double    q;
	double    r;
	double    a_x;
	double    a_y;
	double    a_z;
	double    true_airspeed;
	double    indicated_airspeed;
	double    density;
	double    dynamic_pressure;
	double    barometric_pressure;
	double    height_rate;
	double    height;
	double    ssa;
	double    aoa;
	double    gamma;
	double    phi;
	double    the;
	double    psi;
	double    latitude;
	double    longitude;
	double    posN;
	double    posE;
	double    posD;
	double    speedN;
	double    speedE;
	double    speedD;
	double    windN;
	double    windE;
	double    windD;
	boolean  alive;
};
